### ISSUE TITLE
Incorrect track names when using a single track

### ISSUE THREAD

**Issue by antoine-sachet** [ashbaldry/howler#11]
Hi Ashley - I've been testing out the new htmlwidget implementation and it's really good!

There's a small bug with the track name when creating a howler with a single track. Basically the track name doesn't get stored in an array in the JS when there's only one track. This means that `track_names[current_track]` returns the first letter instead of the first track title! Also it breaks `addTrack` because `track_names.push()` causes an error. 

This is down to this bit of JS:

```
        if (Array.isArray(x.tracks)) {
          tracks = x.tracks;
          track_names = x.names;
          if (x.formats) {
            track_formats = x.formats;
          }
        } else if (x.tracks) {
          tracks = [x.tracks];
          track_names = [x.names];
          if (x.formats) {
            track_formats = [x.formats];
          }
        } else {
          tracks = [];
          track_names = [];
        }
```

It turns out that when there's a single track, the JS receives options like: `tracks: Array(1), names: 'test', ...`. So `tracks` is an array but `names` isn't.

I am using `jsonlite 1.8.0`, maybe this is version-sensitive.

**Comment by ashbaldry** [comment]
Hey Antoine, thanks for all the feedback! 

Had a look into this issue, and think by turning track names and track formats into lists it resolves this issue. I've just added the fix, let me know if it works :)
