### ISSUE TITLE
`add_track` doesn't work if track has a name

### ISSUE THREAD

**Issue by antoine-sachet** [ashbaldry/howler#12]
Hey Ash - I'm back :)

Adding a track with a name doesn't work because Howl expects a string URL and not an object with a name.

We just need to strip the name in R when calling `addHolwerTrack_id`.

Currently the call is `session$sendCustomMessage(message_name, list(track = track, track_name = track_name, play = play_track))` where `track` is a named string. 

Simply adding `unname` (and `as.list` for good measure) fixed the problem:

```
addTrack <- function(id, track, play_track = FALSE, session = getDefaultReactiveDomain()) {
  if (is.null(names(track))) {
    track_name <- sub("\\.[^\\.]+$", "", basename(track[1]))
  } else {
    track_name <- names(track)
  }

  message_name <- paste0("addHowlerTrack_", session$ns(id))
  track_info <- list(track = as.list(unname(track)),
                     track_name = as.list(track_name),
                     play = play_track)
  session$sendCustomMessage(message_name, track_info)
}
```

**Comment by ashbaldry** [comment]
Hi Antoine, thanks for posting this, will look into it 😄

**Comment by ashbaldry** [comment]
@antoine-sachet would you mind testing out the `bugfix/add-track` branch? I've tried to make it so multiple tracks can be added with names.

**Comment by antoine-sachet** [comment]
FYI I tested the new `addTrack()` function with 1 (named) track and it worked well. 

I haven't tried with multiple tracks but, now that the functionality is here, I might use it soon!
