### ISSUE TITLE
New release for v0.2.1

### ISSUE THREAD

**Issue by antoine-sachet** [ashbaldry/howler#16]
Thanks a lot for all the changes you've implemented recently - as far as I can tell, everything is working great!

Could you please make a github release (or at least just a tag v0.1.2) to simplify deployment? This way we can install the package from the "known good" `ashbaldry/howler@v0.2.1`. 

Are you planning a [CRAN release](https://r-pkgs.org/release.html) soon? It'd be great but I appreciate it's a bit of work - happy to help with it if needed :)

**Comment by ashbaldry** [comment]
Glad to hear the fix is working for you!

Knowing that, I'll probably start the release to CRAN in the next couple of days. I didn't realise that I hadn't been attaching the releases for {howler}, but I can add them once tests have come back with no issues 😃

**Comment by ashbaldry** [comment]
0.2.1 is now available on CRAN!
