### ISSUE TITLE
Howler cannot handle URLs with query parameters

### ISSUE THREAD

**Issue by antoine-sachet** [ashbaldry/howler#4]
Thanks for sharing your package (MIT license is ❤️), it's going to be super useful! 

I need to make a number of changes to make it work for my use case, which I'll implement in my fork. I'm going to open a few issues just to document what I intend to change.

Currently, HTTP URLs with query parameters are not handled correctly and cannot be played. 

These are URLs like:

```
http://www.example.com/files/audio.mp3?a=1&b=2
```

Use case: tracks in a private AWS S3 bucket are accessible using presigned URLs which have signature details in such query parameters.

**Comment by antoine-sachet** [comment]
This can be traced to incorrect file type extraction in `howler.shiny.js`.

The code currently does:

```
if (typeof(track) === 'string') {
      if (track.includes('base64,')) {
        return null;
      } else {
        var file_type = track.split('.').pop();
        return file_type === 'mp4' ? 'dolby' : file_type;
      }
    } else {
      return track.map(self.getTrackFormat);
    }
```

and then pass the `file_type` to `Howl` as `format`.

This can be fixed by changing one line to:

```
var file_type = track.split('.').pop().split('?', 1)[0]
```

But I am not sure that `shiny.howler.js` should extract the file type anyway - `Howl` will do it (and handle base64 and query parameters correctly) if `format` is `null`.

I can see that you were handling the special case of dolby audio in mp4 files, which does require passing the format...
It's tricky because it is not true in general that mp4 files should be treated as dolby.  Perhaps there should be a way to pass a `format` argument from R to handle those cases.

Oh well, I'll just fix it for my use case by adding `.split('?', 1)[0]`, but there will remain one bug: you cannot play a non-dolby mp4.

**Comment by ashbaldry** [comment]
Thanks for the support on this!

I have realised I've made it pretty clunky and wanted to rewrite it all using {htmlwidgets} (made a small start in another branch). I took the [original documentation](https://github.com/goldfire/howler.js#dolby-audio-playback) to mean that all mp4s use Dolby rather than only some. Feel free to remove that part of the code when fixing this issue; alternatively I think having an options list will work well to future proof people wanting to add extra options to the `Howl`.

**Comment by antoine-sachet** [comment]
Oh that's nice, I'll check it out! To be honest, your package gets the job done for me now that I have added support for titles and fixed the bug with query parameters. 

I don't think it's that clunky at all and it certainly looks much better than what I had before!

**Comment by ashbaldry** [comment]
Fair enough! All the issues you've been raising has pushed me to finish rewriting it all as a widget. The documentation needs updating still, but I'm hoping it at least fixes this issue (and one or two others you've mentioned).

**Comment by ashbaldry** [comment]
FYI I've updated all the documentation and tests in the `htmlwidget` branch, all seems to work okay, but let me know if any of these issues still arise!

**Comment by antoine-sachet** [comment]
Fixed in the new htmlwidget implementation - thanks!
