### ISSUE TITLE
changeTrack() file argument doesn't match howlerPlayer files

### ISSUE THREAD

**Issue by antoine-sachet** [ashbaldry/howler#6]
`changeTrack()` has a peculiar behaviour: it expects a file name rather than a file path. 

I don't know if it's a bug or if it was on purpose. Perhaps it's for dealing with the case where multiple files are provided for the same track? But these files probably have different extensions, and the extension is part of the file name so it wouldn't help.

This is a bit strange because the `howlerPlayer` is constructed with file paths, and the internal playlist is composed of file paths. It also means that `changeTrack` cannot handle files with the same name in different directories, since we have to strip the directory structure to use it.

Here's an illustration.

```
library(shiny)
library(howler)

audio_files_dir <- system.file("examples/_audio", package = "howler")
addResourcePath("sample_audio", audio_files_dir)
audio_files <- file.path("sample_audio", list.files(audio_files_dir, ".mp3$"))

ui <- fluidPage(
  useHowlerJS(),

  h3("howler changeTrack example"),

  howlerPlayer("sound", audio_files),
  howlerPlayPauseButton("sound"),
  howlerVolumeSlider("sound"),
  howlerCurrentTrack("sound"),
  tags$br(),

  selectInput("selected_track", label = "Select a track", choices = audio_files)
)

server <- function(input, output, session) {

  observeEvent(input$selected_track, {
    # basename is required here, otherwise it won't work
    changeTrack(session, "sound", basename(input$selected_track))
  })
}

shinyApp(ui, server)
```

The example raises an interesting question: what should be the unique identifier of a track? Using the full file path to the audio file makes sense, but it's not necessarily user friendly - and there's always the case where multiple audio files are provided for the same track... 

Perhaps `changeTrack` could take either a file (full file path, matching the internal playlist) or an index (1-based in R, converted to 0-based in JS) so it's easy to move through a playlist.

**Comment by ashbaldry** [comment]
This is now implemented with the {htmlwidgets} version of {howler}, the following works as expected:

```r
library(shiny)
library(howler)

audio_files_dir <- system.file("examples/_audio", package = "howler")
addResourcePath("sample_audio", audio_files_dir)
audio_files <- file.path("sample_audio", list.files(audio_files_dir, ".mp3$"))

ui <- fluidPage(
  h3("howler changeTrack example"),
  
  howler(elementId = "sound", audio_files),
  howlerPlayPauseButton("sound"),
  howlerVolumeSlider("sound"),
  howlerCurrentTrack("sound"),
  tags$br(),
  
  selectInput(
    "selected_track", 
    label = "Select a track", 
    choices = setNames(seq(audio_files), basename(audio_files))
  )
)

server <- function(input, output, session) {
  observeEvent(input$selected_track, ignoreInit = TRUE, {
    changeTrack("sound", input$selected_track)
  })
}

shinyApp(ui, server)
```

You can change the choices to `basename(audio_files)` or `sub("\\..*", "", basename(audio_files))` and it should play the selected track as well
