### ISSUE TITLE
Create empty howlerPlayer

### ISSUE THREAD

**Issue by antoine-sachet** [ashbaldry/howler#7]
In various cases, it'd be useful to create a player with an empty playlist. In my use case, the playlist is constructed later and I have no tracks when the app starts.

One option might be to create the player later, once the first track comes in, but this is is not nice for 2 reasons:
  - I'd rather have the UI of the player all along, even with no tracks
  - It wouldn't work anyway, given that the JS detects the howlerPlayers only once when shiny connects

For these reasons, we should be able to create a howlerPlayer without files (`files = NULL` or `files = list()` or `files = character(0)`).

It might not be straightforward since we can't create a howl without a track, so effectively the `player` element of the `howlerPlayer` would have to be empty, and that is sure to cause some issues with play, plause, etc...

In the meantime, I'm using `files = " "` (not an empty string as that wouldn't work) to get the player started with a dummy track and "invisible" title and that works ok. This empty track stays in the playlist though which is not ideal.

**Comment by ashbaldry** [comment]
I think this is the only issue I'm having a couple of problems with; `Howl` throws an error in JS if `src` is a blank vector. However think I have a workaround to not load until a song is added. Try out the `htmlwidget` branch and let me know.

The way I tried it out was using the ["full" example app](https://github.com/ashbaldry/howler/blob/htmlwidget/inst/examples/full/app.R) and removing the `audio_files` in `howler`, running the app and clicking the button

**Comment by ashbaldry** [comment]
This is now possible by running `howler(tracks = NULL)` and with `addTrack`, audio can be added to the empty player
